# Generated by Django 3.2.8 on 2021-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenciesdata',
            name='amount',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currenciesdata',
            name='currency',
            field=models.CharField(choices=[('DOLLAR', 1), ('EURO', 2)], default='DOLLAR', max_length=100),
        ),
    ]
