# Generated by Django 3.2.8 on 2021-10-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_currenciesdata_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenciesdata',
            name='currency',
            field=models.CharField(choices=[('DOLLAR', 1), ('EURO', 2)], default=1, max_length=100),
        ),
    ]
