# Generated by Django 3.2.8 on 2021-10-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_currenciesdata_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenciesdata',
            name='ratio_of_dollar_on_euro',
            field=models.FloatField(default=0.0, max_length=100),
        ),
    ]
