# Generated by Django 3.2.8 on 2022-07-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_currenciesdata_ratio_of_dollar_on_euro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenciesdata',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currenciesdata',
            name='currency',
            field=models.CharField(choices=[('USD', 1), ('EURO', 2)], default=1, max_length=40),
        ),
    ]
