# Generated by Django 3.2.8 on 2022-07-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20220710_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currenciesdata',
            options={'managed': False},
        ),
    ]
