# Generated by Django 3.2.8 on 2022-07-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_currenciesdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currenciesdata',
            options={},
        ),
    ]
